name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Sync Static Site to S3 + Purge Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Sync static-site/ to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: scalable-static-site.com         # replace if needed
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: static-site                         # your static files should be here

      - name: Purge Cloudflare cache
        uses: mathielo/cloudflare-cache-action@v1        # ✅ working purge action
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
