name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Sync Static Site to S3 + Purge Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Sync static-site/ to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: static-site

      - name: Purge Cloudflare cache
        uses: nathanvaughn/actions-cloudflare-purge@v1.2.0
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
